version: "2"
services:
    timemachine:
        image: dubodubonduponey/netatalk:v1
        restart: unless-stopped
        volumes:
            - /mnt/Storage2/Disk_Time/:/media/timemachine
        environment:
            - USERS=yasser
            - PASSWORDS=*1ion.vale
            - NAME=Disk_Time02
            - AVAHI_NAME=Disk_Time02
        cap_add:
            - NET_BIND_SERVICE
            - CHOWN
            - FOWNER
            - SETUID
            - SETGID
            - DAC_OVERRIDE
        cap_drop:
            - ALL
        network_mode: host
        
### Terminal de mac ###        
#defaults write com.apple.systempreferences TMShowUnsupportedNetworkVolumes 1        
#sudo tmutil setdestination afp://yasser:*1ion.vale@10.10.10.10/Time\ Machine