version: "3"
services:
   samba:
           image: dperson/samba
           restart: always
           command: '-u "yasser;*1ion.pulsar" -s "media;/media;yes;no"'
           stdin_open: true
           tty: true
           ports:
                - 139:139
                - 445:445         
           volumes:
                - /mnt/Storage0:/media

